on:
  push:
    branches:
      -main
  schedule:
#    - cron: 0 */24 * * *   # 每隔24小时
jobs:
  update_external_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: xiaorouji/openwrt-passwall # 上游仓库
          target_repository: starambler/openwrt-passwall # 你要推送的仓库
          upstream_branch: main # 默认拉取分支
          target_branch: main # 默认推送分支
          force: true # 是否强制推送
          tags: true # 确定是否使用-tags
